# app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
#        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject: "true"
#        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-inject-secret-mysecretvault: 'secret/mysecretvault'
        vault.hashicorp.com/agent-inject-secret-path-somepath-to-my-secret: "secret/path-to-my-secret"
        vault.hashicorp.com/agent-inject-secret-helloworld: "secret/helloworld"
        vault.hashicorp.com/agent-inject-template-helloworld: |
          {{- with secret "secret/helloworld" -}}
          export MY_SECRET={{ .Data.data.password }}
          export MY_USERNAME={{ .Data.data.username }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-mysecretvault: |
          {{- with secret "secret/mysecretvault" -}}
          export MY_SECRET={{ .Data.data.secretkey }}
          {{- end }}
      labels:  
        app: vault-agent-demo
    spec:
      serviceAccountName: app
      containers:
        - name: app
#          image: cyberships/pythonapp:0.1
          image: busybox
          ports:
          - containerPort: 8000
          command: ["sh","-c"]
          args: [ 'sleep 1000' ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: demo
  labels:
    app: vault-agent-demo
